# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

# just test
# steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'


variables:
  DOCKER_REGISTRY_CONNECTION: dockerHub-connection
  AZURE_CONNECTION: azure-aca-connection-sp
  IMAGE_REPOSITORY: shengguowu/azure-devops
  DOCKERFILE_PATH: Dockerfile
  TAG: '$(Build.BuildId)'

  CONTAINERAPPS_APP: springboot-hello
  CONTAINERAPPS_ENVIRONMENT: aca-environment
  RESOURCE_GROUP: rg-aca-azure-pipelines
  CONTAINER_PORT: 8080


  
stages:
- stage: Build
  displayName: Build and push image
  jobs:
  - job: maven_build
    steps:
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.17'
        jdkArchitectureOption: 'x64'
        # Junit set to false，beacuse no test
        publishJUnitResults: false
        testResultsFiles: '**/TEST-*.xml'
        goals: 'package'
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(IMAGE_REPOSITORY)
        dockerfile: $(DOCKERFILE_PATH)
        containerRegistry: $(DOCKER_REGISTRY_CONNECTION)
        tags: |
          $(TAG)

- stage: Deploy_to_azure_container_app
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AzureContainerApps@1
      displayName: Deploy new container version
      inputs:
        azureSubscription: '$(AZURE_CONNECTION)'
        imageToDeploy: '$(IMAGE_REPOSITORY):$(TAG)'
        containerAppName: '$(CONTAINERAPPS_APP)'
        resourceGroup: '$(RESOURCE_GROUP)'
        containerAppEnvironment: '$(CONTAINERAPPS_ENVIRONMENT)'
        targetPort: '$(CONTAINER_PORT)'
        ingress: 'external'



