version: 0.2

phases:

  build:
    commands:
      - echo "构建开始"
      - mvn package

  post_build:
    commands:
      - echo "构建后步骤开始"
      # 在这里可以执行任何构建后步骤，例如运行测试或上传构建的工件

artifacts:
  files:
    - 'target/*.jar'

cache:
  paths:
    - '/root/.m2/**/*'
