# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
  release:
    types: [created]

jobs:
  build-jar:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: debug
      run: |
        echo "The repository is ${{ github.repository }}"
        echo "The repository owner is ${{ github.repository_owner }}"
        echo "Triggered by ${{ github.actor }}"
        echo "Workflow run ID is ${{ github.run_id }}"
        echo "Commit SHA is ${{ github.sha }}"
        echo "Event name is ${{ github.event_name }}"
        echo "Branch is ${{ github.ref }}"

    - uses: actions/upload-artifact@v4
      with:
        name: springboot-jar
        path: /home/runner/work/springboot-devops/springboot-devops/target/*


    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: shengguowu/springboot:v0.0.1

